controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      # - finger_joint
  - name: r2_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r2_joint_1
      - r2_joint_1
      - r2_joint_2
      - r2_joint_3
      - r2_joint_4
      - r2_joint_5
      - r2_joint_6
      # - r2_finger_joint
  # - name: dual_arm_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: True
  #   joints:
  #     - r2_joint_1
  #     - r2_joint_2
  #     - r2_joint_3
  #     - r2_joint_4
  #     - r2_joint_5
  #     - r2_joint_6
  #     - r2_finger_joint
  #     - joint_2
  #     - joint_3
  #     - joint_4
  #     - joint_5
  #     - joint_6
  #     - finger_joint

  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: False
    joints:
      - finger_joint

  - name: r2_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: False
    joints:
     - r2_finger_joint